### PR TITLE
Fix console errors since content has a shadow-root

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[src/expense-editor.html, line 188 at r1](https://reviewable.io/reviews/vaadin/expense-manager-demo/88#-LBLFT21-HnX-MZOgFL1:-LBLFT21-HnX-MZOgFL2:b70txzw) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/8784b580e7ce659b30d990f0442dbeb18b35afeb/src/expense-editor.html#L188)):*
> ```HTML
>          */
>         _getDialogChild(selector) {
>           return this.$.dialog.$.overlay.$.content.root.querySelector(selector);
> ```

Should be "shadowRoot" instead of "root"

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/expense-editor.html, line 188 at r1](https://reviewable.io/reviews/vaadin/expense-manager-demo/88#-LBLFT21-HnX-MZOgFL1:-LBLPE2y1xffQ4p9Yn9C:b-896fix) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/8784b580e7ce659b30d990f0442dbeb18b35afeb/src/expense-editor.html#L188)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should be "shadowRoot" instead of "root"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88)*

**Comment by web-padawan** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/expense-editor.html, line 77 at r2](https://reviewable.io/reviews/vaadin/expense-manager-demo/88#-LBLPvDh0BrkOcErv2av:-LBLPvDi9VsSsW1Z5kZo:bzbj09q) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/a4f66f7fcd5944236eff72371d73ecd7eef9bcfe/src/expense-editor.html#L77)):*
> ```HTML
>             <div class="file-list">
>               <div class="receipt-wrapper">
>                 Receipt
> ```

why has the ` been removed

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/expense-editor.html, line 77 at r2](https://reviewable.io/reviews/vaadin/expense-manager-demo/88#-LBLPvDh0BrkOcErv2av:-LBLQPDq6qqhrKXQ-ISd:bliq2m8) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/a4f66f7fcd5944236eff72371d73ecd7eef9bcfe/src/expense-editor.html#L77)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

why has the ` been removed
</blockquote></details>

sorry, I mean "rootPath". It is needed to work with prpl-server, and adds the "/es6-bundled/" folder prefix here

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/expense-editor.html, line 77 at r2](https://reviewable.io/reviews/vaadin/expense-manager-demo/88#-LBLPvDh0BrkOcErv2av:-LBLQzXcE3OP2SgnTG2M:b6e6zm8) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/a4f66f7fcd5944236eff72371d73ecd7eef9bcfe/src/expense-editor.html#L77)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

sorry, I mean "rootPath". It is needed to work with prpl-server, and adds the "/es6-bundled/" folder prefix here
</blockquote></details>

So we need a function here, because it's added also when url is `data:...` will find a solution

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88)*

**Comment by manolo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/expense-editor.html, line 77 at r2](https://reviewable.io/reviews/vaadin/expense-manager-demo/88#-LBLPvDh0BrkOcErv2av:-LBLUUps4gtce_p5ae0i:b-896fix) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/a4f66f7fcd5944236eff72371d73ecd7eef9bcfe/src/expense-editor.html#L77)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

So we need a function here, because it's added also when url is `data:...` will find a solution
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88#-:-LB_XVMa9HOxQT1S1t2-:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88#-:-LB_Z-e--arn0P_q3mmk:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/88)*

**Pull request merged**
