### PR TITLE
Replace paper-icon-button and cleanup styles

### PR DESCRIPTION
**Pull request by web-padawan**
Connected to #59 

- replace `paper-icon-button`
- adjust styles for dialogs
- replace `iron-icons` import with custom iconset
- cleanup unused styles
- add `stylelint` and fix some warnings

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/78)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/78)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/78#-:-L5y-wO_536RwSbAknLB:bnfp4nl)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 13 of 15 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/78#-:-L6-IhJjW7W_c59AnuuJ:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/78)*

**Pull request merged**
