### PR TITLE
Simple dependencies

### LINKED ISSUE #84: Clean up bower.json
Depend on `vaadin-core` instead of individual elements. Remove unused components.

### PR DESCRIPTION
**Pull request by manolo**
Fix #84

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/93)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[bower.json, line 9 at r1](https://reviewable.io/reviews/vaadin/expense-manager-demo/93#-LBf4xUm0Ac4AveNgkOQ:-LBf4nRBC7TBmWMS0zuG:b1vs0qj) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/1075f4d65d646c60d19958a99a3e1555d0ad3ce6/bower.json#L9)):*
> ```JSON
>   "dependencies": {
>     "polymer": "polymer/polymer#^2.0.0",
>     "vaadin-core": "v10.0.0-alpha23",
> ```

the latest one is 10.0.0-beta9 (tagged but with no release notes)

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/93)*

**Comment by manolo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 9 at r1](https://reviewable.io/reviews/vaadin/expense-manager-demo/93#-LBf4xUm0Ac4AveNgkOQ:-LBfEfom8AL_a5NisgZP:bag4grm) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/1075f4d65d646c60d19958a99a3e1555d0ad3ce6/bower.json#L9)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

the latest one is 10.0.0-beta9 (tagged but with no release notes)
</blockquote></details>

thanks. Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/93)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/93)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/93#-:-LBtbb-W6PpWgmFmRa14:bnfp4nl)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[a discussion](https://reviewable.io/reviews/vaadin/expense-manager-demo/93#-LBtemelBeWlh_uGG8ng:-LBtemelBeWlh_uGG8nh:bfqx673) (no related file):*
:confused: 

- Fixed `-betaX` dependency number requires maintenance bumps.
- Some elements are installed but never used, which is a bad practice. We probably shouldn’t advocate that.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/93)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/expense-manager-demo/93#-LBtemelBeWlh_uGG8ng:-LBtnK5lCHkY_2ilvoiM:b-qmaz3o) (no related file):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

:confused: 

- Fixed `-betaX` dependency number requires maintenance bumps.
- Some elements are installed but never used, which is a bad practice. We probably shouldn’t advocate that.
</blockquote></details>

Already raised that question in the issue targeting by this PR. 
I also stand for using only the stuff we really need.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/93)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/expense-manager-demo/93#-LBtemelBeWlh_uGG8ng:-LBtktBI8PWNxLGFuXuD:b14vxhu) (no related file):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

Already raised that question in the issue targeting by this PR. 
I also stand for using only the stuff we really need.
</blockquote></details>

We are encouraging to use vaadin-core in all other starters like base-starter-vue, bakery, etc all of them depends on vaadin-core-betaX and they are updated in each new beta version.  I don't see any reason for this not be aligned with the rest. 
Depending on more stuff does not necessary mean to produce bigger bundle or performance issues when running the app in dev or production, it's just a nit when running bower install which is compensated with the simply setup of the app. 

In my case `bower i` does not produces a significant problem in a 4G network

```
real	0m17.140s
user	0m7.403s
sys	0m3.661s

real	0m22.917s
user	0m11.898s
sys	0m6.105s
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/93)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/expense-manager-demo/93#-LBtemelBeWlh_uGG8ng:-LBu36w43E4jVt2dsRJK:b-q60hgb) (no related file):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

We are encouraging to use vaadin-core in all other starters like base-starter-vue, bakery, etc all of them depends on vaadin-core-betaX and they are updated in each new beta version.  I don't see any reason for this not be aligned with the rest. 
Depending on more stuff does not necessary mean to produce bigger bundle or performance issues when running the app in dev or production, it's just a nit when running bower install which is compensated with the simply setup of the app. 

In my case `bower i` does not produces a significant problem in a 4G network

```
real	0m17.140s
user	0m7.403s
sys	0m3.661s

real	0m22.917s
user	0m11.898s
sys	0m6.105s
```

</blockquote></details>

OK not a blocker to me, let's align with the other starters.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/93)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/expense-manager-demo/93#-LBtemelBeWlh_uGG8ng:-LBzjAC6-LNJCcNfJ6mA:b-b1u4cv) (no related file):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

OK not a blocker to me, let's align with the other starters.
</blockquote></details>

OK :see_no_evil: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/93)*

**Pull request merged**
