### PR TITLE
Fix login page layout. Prevent layout jump

### PR DESCRIPTION
**Pull request by web-padawan**
- removed the `height: 36%` causing problems on mobile devices
- updated login page layout to use flex box
- changed `body` background back to dark one,to prevent background flash when switching pages
- added `background` and `color` for some elements previously inherited those properties from body
- changed `nav-bar` to prevent noticeable layout jump when switching from login page, it appears that `justify-content: flex-end` works better in this case

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/81)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/login-page.html, line 24 at r1](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/81#-L6GZMfj2jZVByykUuPN:-L6GZMfj2jZVByykUuPO:b-kl9fgz) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/de204f0fccf79cca7fe8720b32f158c525f2d76a/src/login-page.html#L24)):*
> ```HTML
>         justify-content: center;
>         height: calc(100% - var(--lumo-size-l));
>         min-height: 360px;
> ```

We could probably omit the magic number min-height and calc height here:

```css
:host, .wrapper {
  display: flex;
  flex-direction: column;
}

.wrapper {
  justify-content: center;
  flex: 1 0 auto;
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/81)*

**Comment by web-padawan** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/login-page.html, line 24 at r1](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/81#-L6GZMfj2jZVByykUuPN:-L6Gv7pZkOZsMbEgHvM7:bt6436h) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/de204f0fccf79cca7fe8720b32f158c525f2d76a/src/login-page.html#L24)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

We could probably omit the magic number min-height and calc height here:

```css
:host, .wrapper {
  display: flex;
  flex-direction: column;
}

.wrapper {
  justify-content: center;
  flex: 1 0 auto;
}
```


</blockquote></details>

Replaced the magic number with another flex container. Using `:host` as such can sometimes cause unexpected behaviour, because `iron-a11y-keys` element does not apply `display: none` to itself and therefore would be a flex child.

Also, the additional flex container allows to mitigate [flexbug #3](https://github.com/philipwalton/flexbugs#flexbug-3) for IE11.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/81)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/81#-:-L6H27jd-4hG9tl_QmWr:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/81)*

**Pull request merged**
