### PR TITLE
fix flex in dialog content on ie11

### LINKED ISSUE #108: Dialog content is not visible on IE11
The content of the expense dialog is not visible on IE11. @YuriyVaadin investigated this and found that the issue is the use of `flex` https://github.com/vaadin/expense-manager-demo/blob/master/src/shared-styles.html#L34

### PR DESCRIPTION
**Pull request by manolo**
Fixes #108 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/109)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @manolo)

---

*[src/shared-styles.html, line 34 at r1](https://reviewable.io/reviews/vaadin/expense-manager-demo/109#-LFLaNCvAVAXDqFik07_:-LFLaNCvAVAXDqFik07a:b-myvth6) ([raw file](https://github.com/vaadin/expense-manager-demo/blob/d43a3621411e7ba09428056d1bffa148be869c2a/src/shared-styles.html#L34)):*
> ```HTML
> 
>       [part="content"] {
>         display: 1 0 auto;
> ```

incorrect property value

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/109)*

**Comment by yuriy-fix** [comment]
I have reimplemented the solution in scope of this PR.

**Comment by web-padawan** [comment]
Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/109)*

**Comment by tomivirkki** [comment]
screen shot 2018-06-21 at 12 49 54

This PR fixes the issue with IE but it breaks the layout for Edge (screenshot above)

**Comment by yuriy-fix** [comment]
After long investigation, we came up with the decision to use `display: flex` on overlay parts.

---

Review status: 1 of 3 files reviewed, all discussions resolved (waiting on @web-padawan)

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/109#-:-LFv9r-Q9_J2oNP2Vlsd:b5gdsy5)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 2 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/109#-:-LG-62lt2RKkZD-bFOVy:bnfp4nl)*

**Pull request merged**
