### PR TITLE
Apply class naming and namespace conventions

### LINKED ISSUE #66: Using single namespace for classes

### PR DESCRIPTION
**Pull request by platosha**
Fixes #66

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/71)

### CODE REVIEW

**Comment by manolo** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/71)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/71#-L4jG9sA1u8_wc6OS3Vn:-L4jG9sA1u8_wc6OS3Vo:b-yxnhne) (no related file):*
These changes bring in an additional namespace, but since the classes are still globally available (not scoped), I'm not quite sure it brings extra value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/71)*

**Comment by platosha** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/71#-L4jG9sA1u8_wc6OS3Vn:-L4piSPPonmobpHk8skx:btv73xm) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

These changes bring in an additional namespace, but since the classes are still globally available (not scoped), I'm not quite sure it brings extra value
</blockquote></details>

 OK classes are wrapped with IIFEs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/71)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/expense-manager-demo/71#-:-L4tOb3UU9GbZRunS-5h:bnfp4nl)*

**Pull request merged**
