### PR TITLE
Add aria-label="Add expense" for #add-button

### LINKED ISSUE #91: "Add expence" button isn't accessible
`aria-label` is missing for `#add-button`, it's pronounced as "clickable button" by screen readers.

### PR DESCRIPTION
**Pull request by limonte**
Fixes #91

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/92)

### CODE REVIEW

**Comment by manolo** [comment]
:lgtm: needs also to be applied to the pro version 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/92#-:-LBed9_95IOTptuF7YrD:buruqst)*

**Comment by limonte** [comment]
Done: https://github.com/vaadin/expense-manager-demo-pro/pull/16

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/92#-:-LBeeDN398ww1y0vmvL3:bimt913)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/92#-:-LBehvB7AcP0pt3KT1ZK:bnfp4nl)*

**Comment by yuriy-fix** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/92)*

**Pull request merged**
