### PR TITLE
Remove charts view.

### LINKED ISSUE #99: Why the text "Vaadin Charts will be displayed in Pro version"
It seems quite random and not something I would really want to have in my new project?

### PR DESCRIPTION
**Pull request by manolo**
Fixes #99

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/102)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/102#-:-LDpP2_GCPHDkz-REkVo:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[a discussion](https://reviewable.io/reviews/vaadin/expense-manager-demo/102#-LDpVHiy-EIQE21y1tcE:-LDpVHiy-EIQE21y1tcF:b-tmslcj) (no related file):*
Why was the "To be reimbursed" part removed?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/102)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/expense-manager-demo/102#-LDpVHiy-EIQE21y1tcE:-LDpe5_iAsI74dmbh9ZI:b-jvbo1q) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why was the "To be reimbursed" part removed?
</blockquote></details>

I thought it was part of the statistics panel with charts. But yes it gives some info so restored back.
Probably without charts, the amount of code necessary for showing just a sum result is unnecessary, but that is different story. 

Restored it. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/102)*

**Comment by yuriy-fix** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/expense-manager-demo/102#-:-LDpEmg49hhCyfXC9IcX:bnfp4nl)*

**Pull request merged**
